export enum RESPONSE_CODE {
  SUCCESS = '200',
  ERROR = '-1',

  TOKEN_EXPIRED = '401',
  NOT_FOUND = '404',
  ERROR_REQUEST = '400',

  ERR_CANCELED = 'ERR_CANCELED',
  REQUEST_IGNORE = 'REQUEST_IGNORE',
}
